BEGIN TRANSACTION;
INSERT INTO "glossary_field" VALUES (1,'results');
INSERT INTO "glossary_field" VALUES (2,'home');
INSERT INTO "glossary_field" VALUES (3,'res-title');
INSERT INTO "glossary_field" VALUES (4,'res-algorithm');
INSERT INTO "glossary_field" VALUES (5,'res-simple');
INSERT INTO "glossary_field" VALUES (6,'res-weekly');
INSERT INTO "glossary_field" VALUES (7,'res-overbooking');
INSERT INTO "glossary_field" VALUES (8,'home-metrics_selection');
INSERT INTO "glossary_field" VALUES (9,'home-RoomlessLessons');
INSERT INTO "glossary_field" VALUES (10,'home-Overbooking');
INSERT INTO "glossary_field" VALUES (11,'home-Underbooking');
INSERT INTO "glossary_field" VALUES (12,'home-BadClassroom');
INSERT INTO "glossary_field" VALUES (13,'home-Gaps');
INSERT INTO "glossary_field" VALUES (14,'home-RoomMovements');
INSERT INTO "glossary_field" VALUES (15,'home-BuildingMovements');
INSERT INTO "glossary_field" VALUES (16,'home-UsedRooms');
INSERT INTO "glossary_field" VALUES (17,'home-ClassroomInconsistency');
INSERT INTO "glossary_field" VALUES (18,'home-changes_to_file');
INSERT INTO "glossary_field" VALUES (19,'home-RoomlessLessons_max');
INSERT INTO "glossary_field" VALUES (20,'home-Overbooking_max');
INSERT INTO "glossary_field" VALUES (21,'home-Underbooking_max');
INSERT INTO "glossary_field" VALUES (22,'home-BadClassroom_max');
INSERT INTO "glossary_field" VALUES (23,'home-degree');
INSERT INTO "glossary_field" VALUES (24,'home-subject');
INSERT INTO "glossary_field" VALUES (25,'home-shift');
INSERT INTO "glossary_field" VALUES (26,'home-grade');
INSERT INTO "glossary_field" VALUES (27,'home-enrolled');
INSERT INTO "glossary_field" VALUES (28,'home-day_week');
INSERT INTO "glossary_field" VALUES (29,'home-begins_at');
INSERT INTO "glossary_field" VALUES (30,'home-ends');
INSERT INTO "glossary_field" VALUES (31,'home-day');
INSERT INTO "glossary_field" VALUES (32,'home-characteristics_asked');
INSERT INTO "glossary_field" VALUES (33,'home-classroom');
INSERT INTO "glossary_field" VALUES (34,'home-max_capacity');
INSERT INTO "glossary_field" VALUES (35,'home-characteristics_actual');
INSERT INTO "glossary_field" VALUES (36,'home-select_schedule');
INSERT INTO "glossary_content" VALUES (64,2,1,'Resultados');
INSERT INTO "glossary_content" VALUES (65,2,2,'Início');
INSERT INTO "glossary_content" VALUES (66,2,3,'Otimizador de Horários');
INSERT INTO "glossary_content" VALUES (67,2,4,'Transferir o melhor algoritmo de alocação');
INSERT INTO "glossary_content" VALUES (68,2,5,'Primeira sala que cumpra os requisitos preenche a sala');
INSERT INTO "glossary_content" VALUES (69,2,6,'A melhor sala para a aula e para as mesmas aulas em diferentes semanas');
INSERT INTO "glossary_content" VALUES (70,2,7,'Alocar aulas a salas se todos os requisitos forem preenchidos. Melhorado para horários problemáticos');
INSERT INTO "glossary_content" VALUES (71,2,8,'Seleção de critérios de escolha de melhor algoritmo');
INSERT INTO "glossary_content" VALUES (72,2,9,'Aulas sem sala');
INSERT INTO "glossary_content" VALUES (73,2,10,'Sobre-alocação');
INSERT INTO "glossary_content" VALUES (74,2,11,'Sub-alocação');
INSERT INTO "glossary_content" VALUES (75,2,12,'Má sala');
INSERT INTO "glossary_content" VALUES (76,2,13,'Buracos');
INSERT INTO "glossary_content" VALUES (77,2,14,'Movimentos entre salas');
INSERT INTO "glossary_content" VALUES (78,2,15,'Movimentos entre edifícios');
INSERT INTO "glossary_content" VALUES (79,2,16,'Salas utilizadas');
INSERT INTO "glossary_content" VALUES (80,2,17,'Inconsistência nas salas');
INSERT INTO "glossary_content" VALUES (81,2,18,'Houve alterações ao ficheiro?');
INSERT INTO "glossary_content" VALUES (82,2,19,'Limite máximo para aulas sem sala');
INSERT INTO "glossary_content" VALUES (83,2,20,'Limite máximo para sobre-alocação');
INSERT INTO "glossary_content" VALUES (84,2,21,'Limite máximo para sub-alocação');
INSERT INTO "glossary_content" VALUES (85,2,22,'Limite máximo para má salas');
INSERT INTO "glossary_content" VALUES (86,2,23,'Curso');
INSERT INTO "glossary_content" VALUES (87,2,24,'Unidade de Execução');
INSERT INTO "glossary_content" VALUES (88,2,25,'Turno');
INSERT INTO "glossary_content" VALUES (89,2,26,'Turma');
INSERT INTO "glossary_content" VALUES (90,2,27,'Inscritos no turno');
INSERT INTO "glossary_content" VALUES (91,2,28,'Dia da Semana');
INSERT INTO "glossary_content" VALUES (92,2,29,'Início');
INSERT INTO "glossary_content" VALUES (93,2,30,'Fim');
INSERT INTO "glossary_content" VALUES (94,2,31,'Dia');
INSERT INTO "glossary_content" VALUES (95,2,32,'Características da sala pedida para a aula');
INSERT INTO "glossary_content" VALUES (96,2,33,'Sala');
INSERT INTO "glossary_content" VALUES (97,2,34,'Lotação Máxima');
INSERT INTO "glossary_content" VALUES (98,2,35,'Características reais da sala');
INSERT INTO "glossary_content" VALUES (99,2,36,'Anexe o horário para análise');
INSERT INTO "glossary_content" VALUES (100,1,1,'Results');
INSERT INTO "glossary_content" VALUES (101,1,2,'Home');
INSERT INTO "glossary_content" VALUES (102,1,3,'Schedule Optimizer');
INSERT INTO "glossary_content" VALUES (103,1,4,'Download the best allocation algorithm ');
INSERT INTO "glossary_content" VALUES (104,1,5,'First classroom which fulfills the requirements asked');
INSERT INTO "glossary_content" VALUES (105,1,6,'The best classroom for the lesson and for the same lessons in different weeks');
INSERT INTO "glossary_content" VALUES (106,1,7,'Allocate lessons to classrooms if all requirements are fulfilled. Improved for problematic schedules');
INSERT INTO "glossary_content" VALUES (107,1,8,'Criteria for the selection of the best algorithm');
INSERT INTO "glossary_content" VALUES (108,1,9,'Lessons without classroom');
INSERT INTO "glossary_content" VALUES (109,1,10,'Overbooking');
INSERT INTO "glossary_content" VALUES (110,1,11,'Underbooking');
INSERT INTO "glossary_content" VALUES (111,1,12,'Bad classroom');
INSERT INTO "glossary_content" VALUES (112,1,13,'Gaps');
INSERT INTO "glossary_content" VALUES (113,1,14,'Room movements');
INSERT INTO "glossary_content" VALUES (114,1,15,'Building movements');
INSERT INTO "glossary_content" VALUES (115,1,16,'Used rooms');
INSERT INTO "glossary_content" VALUES (116,1,17,'Classroom inconsistency');
INSERT INTO "glossary_content" VALUES (117,1,18,'Were there changes made to the file?');
INSERT INTO "glossary_content" VALUES (118,1,19,'Maximum threshold for lessons without a room');
INSERT INTO "glossary_content" VALUES (119,1,20,'Maximum threshold for overbooking');
INSERT INTO "glossary_content" VALUES (120,1,21,'Maximum threshold for underbooking');
INSERT INTO "glossary_content" VALUES (121,1,22,'Maximum threshold for bad classrooms');
INSERT INTO "glossary_content" VALUES (122,1,23,'Degree');
INSERT INTO "glossary_content" VALUES (123,1,24,'Subject');
INSERT INTO "glossary_content" VALUES (124,1,25,'Shift');
INSERT INTO "glossary_content" VALUES (125,1,26,'Grade');
INSERT INTO "glossary_content" VALUES (126,1,27,'Enrolled');
INSERT INTO "glossary_content" VALUES (127,1,28,'Day of the week');
INSERT INTO "glossary_content" VALUES (128,1,29,'Begins at');
INSERT INTO "glossary_content" VALUES (129,1,30,'Ends');
INSERT INTO "glossary_content" VALUES (130,1,31,'Day');
INSERT INTO "glossary_content" VALUES (131,1,32,'Classroom characteristics asked for the lesson');
INSERT INTO "glossary_content" VALUES (132,1,33,'Classroom');
INSERT INTO "glossary_content" VALUES (133,1,34,'Maximum capacity');
INSERT INTO "glossary_content" VALUES (134,1,35,'Actual characteristics of the classroom');
INSERT INTO "glossary_content" VALUES (135,1,36,'Upload the schedule for further analysis');
INSERT INTO "glossary_language" VALUES (1,'en','English');
INSERT INTO "glossary_language" VALUES (2,'pt','Portuguese');
COMMIT;
