# Generated by Django 4.0 on 2021-12-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField()),
                ('page_field', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'glossary_content',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlossaryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_field', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'glossary_field',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlossaryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('language_full', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'glossary_language',
                'managed': True,
            },
        ),
    ]
